CREATE DATABASE bdCRUD;

USE bdCRUD;

CREATE TABLE bdCRUD.usuarios (
    id INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    data_nascimento DATE NOT NULL,
    senha VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (id)
);
SELECT * FROM usuarios;